version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # הצינור שמוציא את הקבצים מהכספת של דוקר ישירות לתיקייה שלך
      - ./data:/app/data
    restart: unless-stopped